@baseUrl = http://localhost:5000
@urlPath = api/v1



### Send Request
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "68b838759fe423c06ffd6864",
  "postId": "68bd6973166231cd819755e1",
  "type": "happy",
  "previousReaction": "love",
  "postReactions": {
    "like": 0,
    "love": 0,
    "happy": 1,
    "sad": 0,
    "wow": 0,
    "angry": 0
  },
  "profilePicture": "https://res.cloudinary.com/dyamr9ym3/image/upload/v1659189696/62e539c0d8b514f6e42e3b5b"
}


### Send Request
DELETE  {{baseUrl}}/{{urlPath}}/post/reaction/68b838cf9fe423c06ffd686d/happy/	{"like":0,"love":0,"happy":0,"sad":0,"wow":0,"angry":0}
Content-Type: application/json
Accept: application/json
withCredentials: true


### Send Request
GET  {{baseUrl}}/{{urlPath}}/post/reactions/68bd6973166231cd819755e1
Content-Type: application/json
Accept: application/json
withCredentials: true
